import { chromium } from "playwright";
import { readFile, writeFile } from "node:fs/promises";
const [inp, out] = process.argv.slice(2);
const svg = await readFile(inp, "utf8");
const b = await chromium.launch({ channel: "msedge" });
const p = await b.newPage({ viewport: { width: 1000, height: 300 } });
await p.setContent(`<body style="margin:0">${svg}</body>`);
const el = await p.$("svg");
await writeFile(out, await el.screenshot());
await b.close();
console.log("→", out);
